version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: lms_db
    environment:
      - POSTGRES_DB=lms_db
      - POSTGRES_USER=lms_user
      - POSTGRES_PASSWORD=lms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lms_user -d lms_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
